input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "camunda-logs-%{+YYYY.MM.dd}"
  }
  # Debug log ra console của Logstash để bạn dễ kiểm tra lúc đầu
  stdout { codec => rubydebug }
}